name: Build and Deploy

on:
  push:
    branches:
      - main  # Set this to the branch you want to trigger the build from

jobs:
  build-and-deploy:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout Code
        uses: actions/checkout@v3

      - name: Set up Node.js
        uses: actions/setup-node@v3
        with:
          node-version: '16'  # Set this to your project's required node version

      - name: Install Dependencies
        run: npm install

      - name: Run Build
        run: npm run build

      - name: Deploy Build Directory
        run: |
          git config --global user.email "janpark@hotmail.com"
          git config --global user.name "Jan Park"
          git checkout --orphan build-only
          # Temporarily move the build directory to preserve its contents
          mv build ../build-temp
          # Remove all files in the current directory
          git rm -rf .
          # Bring back the build directory
          mv ../build-temp build
          git add build
          git commit -m "Deploy build directory"
          git push origin build-only --force

